[INLONG-810] Sort Module Support store data to ApacheDoris
apache/incubator-inlong pull request #1846
Opened 2021-11-26 08:34 UTC by huzk8

### Title Name: [INLONG-XYZ][component] Title of the pull request

where *XYZ* should be replaced by the actual issue number.

Fixes #1821 
### Motivation

add sort support doris sink 

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? ( docs )
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2021-11-26 09:41 UTC, dockerzhang commented on inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/doris/TestDorisSink.java
> +				.setFeNodes("10.93.6.6:8030")
it's  a reveal address？

2021-11-29 01:35 UTC, dockerzhang commented
```
[INFO] 开始检查……
Error:  /home/runner/work/incubator-inlong/incubator-inlong/inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/DorisSinkInfo.java:77: 'METHOD_DEF' 前只应有一个空行。 [EmptyLineSeparator]
检查完成。
[INFO] There is 1 error reported by Checkstyle 8.29 with codestyle/checkstyle.xml ruleset.
Error:  src/main/java/org/apache/inlong/sort/protocol/sink/DorisSinkInfo.java:[77] (whitespace) EmptyLineSeparator: 'METHOD_DEF' 前只应有一个空行。
```
@huzk8  please check this error, thanks.

2021-11-29 09:56 UTC, ifndef-SleePy commented
Hi @huzk8 , thanks for contributing!
It's nice to support Doris sink for INLONG project. It looks good to me although I'm not an expert of Doris. I think it's fine to merge the PR first and to tune it later if necessary.
So +1 for me.

2021-11-29 09:59 UTC, dockerzhang approved these changes
LGTM

2021-11-29 10:52 UTC, gosonzhang requested changes

2021-11-29 10:52 UTC, gosonzhang commented on inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisRespond.java
> + * @program: incubator-inlong
After the class function is annotated, the author and creation time need to be removed

2021-11-29 10:53 UTC, gosonzhang commented on inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/BeInfoResponse.java
> + * @author: huzekang
the same problem

2021-11-30 10:51 UTC, gosonzhang commented
@huzk8,  there are several review comments that you need to modify

2021-12-02 01:57 UTC, dockerzhang commented
@huzk8 do you plan to fix the last problems according to the review comments？ We will release the next version in two weeks, and we hope this PR can be merged.

2021-12-02 11:20 UTC, huzk8 commented
> @huzk8, there are several review comments that you need to modify

the `inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisRespond.java` is already modify in commit #e3fe9df

2021-12-02 11:22 UTC, huzk8 commented
> @huzk8, there are several review comments that you need to modify

could you tell me more detail about which file need to modify

2021-12-03 02:51 UTC, gosonzhang approved these changes
+1

2021-12-03 02:52 UTC, merged

2021-12-03 02:54 UTC, dockerzhang commented
@huzk8 thanks for this contribution.