[INLONG-2624][Dashboard] Modify the interface and parameters to adapt to changes in the Manager
apache/incubator-inlong pull request #2629
Opened 2022-02-21 08:17 UTC by healchow

### Title Name: [INLONG-2624][Dashboard] Modify the interface and parameters to adapt to changes in the Manager

Fixes #2624 

### Motivation

Modify the interface and parameters to adapt to changes in the Manager.

### Verifying this change

- [X] Make sure that the change passes the CI checks.

This change is a trivial rework/code cleanup without any test coverage.

### Documentation

  - Does this pull request introduces a new feature? no

2022-02-21 09:10 UTC, dockerzhang approved these changes

2022-02-21 12:04 UTC, leezng requested changes

2022-02-21 13:37 UTC, healchow commented on inlong-dashboard/src/pages/AccessCreate/DataStream/helper.ts
> +      sinkInfo = [],
OK, I rename this field to `streamSink`, as the `dataStorage` was changed to `streamSink` in the Manager module.

2022-02-22 02:36 UTC, gosonzhang approved these changes

2022-02-22 02:37 UTC, merged