[InLong-4227][Sort] Sort lightwieght support extract data to ClickHouse
apache/incubator-inlong pull request #4249
Opened 2022-05-18 09:28 UTC by thexiay

### Title Name: [INLONG-4227][Sort] Sort lightwieght support extract data to clickhouse

Fixes #4227
### Motivation

Sort lightwieght support extract data to clickhouse

### Modifications

Add clickhouse load node.
Add jdbc-inlong table factory to enhance custom jdbc dialect.
Add Clickhouse jdbcdialect.

2022-05-18 10:44 UTC, gong approved these changes

2022-05-18 11:25 UTC, thexiay commented on inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/clickhouse/table/ClickHouseDialect.java
> +    // Define MAX/MIN precision of DECIMAL type according to Mysql docs:
`Mysql` change to `ClcikHouse`

2022-05-18 14:46 UTC, healchow requested changes

2022-05-18 14:46 UTC, healchow commented on inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/ClickHouseSqlParserTest.java
> +        // if you hope hive load mode of append, please add this config
Why use `hive` here?

2022-05-19 04:02 UTC, yunqingmoswu commented on inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/jdbc/table/AbstractJdbcDialect.java
> +public abstract class AbstractJdbcDialect implements JdbcDialect {
Please add some java comments.

2022-05-19 04:02 UTC, yunqingmoswu commented on inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/jdbc/table/JdbcDialects.java
> +/** Default JDBC dialects. */
Check if this comment is normative?

2022-05-19 04:14 UTC, thexiay commented on inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/PostgresConstant.java
> +    public static final String JDBC = "jdbc-inlong";
all jdbc connector both use jdbc-inlong conenctor

2022-05-19 04:14 UTC, thexiay commented on inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/ClickHouseSqlParserTest.java
> +        // if you hope hive load mode of append, please add this config
comment error

2022-05-19 04:41 UTC, thexiay commented on inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
> +        return super.getPrimaryKey();
clickhouse don's support upsert, jdbc relay on primary key to support upsert，so here we should not define clickhouse table a primary key.

2022-05-19 05:11 UTC, yunqingmoswu approved these changes

2022-05-19 05:11 UTC, yunqingmoswu commented on inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
> +        return super.getPrimaryKey();
ok.

2022-05-19 07:26 UTC, thexiay commented
i upgrade flink-sql-connector-postgres-cdc version because 2.0.1 version contains kafka code conflict with kafka-client.It's Qualified class name is same.

2022-05-20 08:18 UTC, EMsnap approved these changes

2022-05-20 08:23 UTC, healchow approved these changes
LGTM

2022-05-20 08:23 UTC, merged